version: '3.8'
services:
  api:
    restart: unless-stopped
    build:
      context: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      FIREBASE_CREDENTIALS: /keys/firebaseKey.json
    volumes:
      - ./keys/firebaseKey.json:/keys/firebaseKey.json:ro
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
