services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # El código se copia a /app (ver backend/Dockerfile). Trabajar ahí.
    working_dir: /app
    # Ejecutar la aplicación v2 (main_v2.py) para exponer routers modernizados (/api/v2/...)
    command: uvicorn main_v2:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # Habilita imports desde /app (p.ej. config, routes, models)
      PYTHONPATH: /app
      FIREBASE_CREDENTIALS: /keys/firebase.json
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
      - ./keys/firebase.json:/keys/firebase.json:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:80"
    restart: unless-stopped
