name: Smoke Tests (backend)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest httpx

      - name: Run smoke runner
        env:
          FIREBASE_CREDENTIALS: ${{ github.workspace }}/keys/firebase.json
        run: |
          python backend/tests/run_smoke.py
