name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
      - name: Install test requirements
        run: |
          python -m pip install -r backend/requirements-tests.txt
      - name: Run pytest
        working-directory: .
        run: |
          PYTHONPATH=backend python -m pytest backend/tests -vv
